version: '2'

services:
  db:
    image: postgres:15.0-alpine
  ci:
    build: .
    depends_on:
      - db
    environment:
      - COVERAGE
      - RAILS_ENV
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    command: sh -c "bundle exec rails db:create db:migrate && bundle exec rake test"

