version: '3.7'

services:
  web:
    build: .
    volumes: &web-volumes
      - &app-volume .:/depot:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - &bundle-cache-volume bundle_cache:/bundle_cache
    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
    depends_on:
      - db
      - redis
    environment: &web-environment
      BUNDLE_PATH: /bundle_cache
      GEM_HOME: /bundle_cache
      GEM_PATH: /bundle_cache
      RAILS_PORT: 3000
      RUBYOPT: -W:no-deprecated -W:no-experimental
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      REDIS_URL: redis://redis
    command: bundle exec ./bin/dev
    links:
      - chrome-server

  chrome-server:
    image: selenium/standalone-chrome:96.0
    ports:
      - "7900:7900"

  db:
    image: postgres:15.0-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:6.2-alpine

volumes:
  bundle_cache:
