version: '2'

services:
  db:
    image: postgres:15
  ci:
    build: .
    depends_on:
      - db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
      - COVERAGE
      - RAILS_ENV
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
    command: sh -c "bundle exec rails db:create db:migrate && bundle exec rake test"
